#!/bin/bash

VERBOSE=${VERBOSE:-false}
MODCERT="$0"
TARGETS=( "$@" )

BEG="-----BEGIN"
KEY="-----BEGIN RSA PRIVATE KEY-----"
CSR="-----BEGIN CERTIFICATE REQUEST-----"
CRT="-----BEGIN CERTIFICATE-----"
PWD="Proc-Type: 4,ENCRYPTED"

declare -A LINES=( \
    ["$KEY"]="rsa" \
    ["$CSR"]="req" \
    ["$CRT"]="x509" \
)

for target in "${TARGETS[@]}"; do
    modhash=""
    if [ -d "$target" ]; then
        $MODCERT `find $target -maxdepth 1 -mindepth 1 -print0 | xargs -0 echo`
        continue
    elif [ -f "$target" ]; then
        line="`grep -F -- "$BEG" "$target" | head -1`"
        action=
        modhash="|---non-openssl-related-file---|"
        if [ -n "$line" ]; then
            action="${LINES[$line]}"
            modhash="|---unknown-openssl-file-type--|"
            if [ -n "$action" ]; then
                if [ "$action" == "rsa" ] && grep -Fxq -- "$PWD" "$target"; then
                    modhash="|----password-protected-rsa----|"
                else
                    modhash="`openssl $action -in $target -noout -modulus 2>/dev/null | md5sum | awk '{print $1}'`"
                fi
            fi
        fi
    fi
    printf "%s %-4s %s\n" $modhash ${action:-NULL} $target
done
