#!/bin/bash
# based off of src: https://gist.github.com/gene1wood/6530100

if [ -n "$DEBUG" ]; then
    PS4=':${LINENO}+'
    set -x
fi

if ! hash host 2> /dev/null; then
    echo "host not installed..."
    exit 1
fi

if ! hash openssl 2> /dev/null; then
    echo "openssl not installed..."
    exit 1
fi

if [ -t 0 ]; then
    if [[ "$1" == *":"* ]]; then
        HOST="${1%%:*}"
        PORT="${1#*:}"
    else
        HOST="$1"
        PORT="443"
    fi
    if [[ $(host "$HOST") != *"not found"* ]]; then
        echo -n | openssl s_client -connect "$HOST:$PORT" -servername "$HOST" 2> /dev/null | openssl x509 -text
        exit 0
    elif [ ! -f "$1" ]; then
        echo "invalid: $1"
        exit 1
    fi
fi

while read line; do
    if [ -z "$TEXT" ]; then
        if [ "$line" == "-----BEGIN CERTIFICATE-----" ]; then
            action="x509"
        elif [ "$line" == "-----BEGIN CERTIFICATE REQUEST-----" ]; then
            action="req"
        elif [ "$line" == "-----BEGIN RSA PRIVATE KEY-----" ]; then
            action="rsa"
        fi
        TEXT="$line\n"
    else
        TEXT="$TEXT$line\n"
    fi
done < "${1:-/dev/stdin}"

if [ -n "$TEXT" ] && [ -n "$action" ]; then
    printf '%b' "$TEXT" | openssl $action -in /dev/stdin -noout -text
else
    echo "ERROR"
    exit 1
fi
